import { doc, setDoc, serverTimestamp } from 'firebase/firestore';
import { db } from './firebase';

/**
 * Gets or creates a conversation between two users using a deterministic ID.
 * The conversation ID is generated by sorting the user IDs and joining with "_".
 * 
 * @param {string} currentUserId 
 * @param {string} otherUserId 
 * @returns {Promise<string>} The conversation ID
 */
export async function getOrCreateConversation(currentUserId, otherUserId) {
    if (!currentUserId || !otherUserId) {
        console.log('[getOrCreateConversation] Missing user IDs:', { currentUserId, otherUserId });
        return null;
    }

    // Generate deterministic conversation ID
    const conversationId = [currentUserId, otherUserId].sort().join("_");
    console.log('[getOrCreateConversation] Using deterministic conversation ID:', conversationId);

    try {
        // Create or update conversation document (merge: true ensures no overwrite)
        const conversationRef = doc(db, 'conversations', conversationId);
        await setDoc(conversationRef, {
            participants: [currentUserId, otherUserId],
            createdAt: serverTimestamp(),
            lastMessage: "",
            lastMessageTimestamp: serverTimestamp(),
        }, { merge: true });

        console.log('[getOrCreateConversation] Conversation ready:', conversationId);
        return conversationId;
    } catch (error) {
        console.error('[getOrCreateConversation] Error:', error);
        return null;
    }
}
